---
title: "Delta Airlines Fleet segmentation"
author: "Hwansoo Joo / Ji Eun Seo / Rahul Gaur / Atul Shukla"
date: "28-01-2017"
Data: "from Delta.com"
output: html_document
---

```{r setup, include=FALSE}
data <- read.csv(file="delta.csv", header=T, sep=",", row.names=1)
```

# scatterplot matrix of intermediary (size/non-categorical) variables

```{r}
plot(data[,16:22])
```

## # Naively apply principal components analysis to raw data and plot


```{r}
pc <- princomp(data)
plot(pc)
```

# First component dominates greatly. What are the loadings?
```{r}
summary(pc) # 1 component has > 99% variance
```


```{r}
loadings(pc) # Can see all variance is in the range in miles 
```

# verify by plotting variance of columns

```{r}
mar <- par()$mar
par(mar=mar+c(0,5,0,0))
barplot(sapply(data, var), horiz=T, las=1, cex.names=0.8)
```

```{r}
barplot(sapply(data, var), horiz=T, las=1, cex.names=0.8, log='x')
```

```{r}
par(mar=mar)
# Scale
data2 <- data.frame(scale(data))
# Verify variance is uniform
plot(sapply(data2, var))
```

```{r}
# Proceed with principal components
pc <- princomp(data2)
plot(pc)
```

```{r}
plot(pc, type='l')
```

```{r}
summary(pc) # 4 components is both 'elbow' and explains >85% variance
```

```{r}
# Get principal component vectors using prcomp instead of princomp
pc <- prcomp(data2)

# First for principal components
comp <- data.frame(pc$x[,1:4])
# Plot
plot(comp, pch=16, col=rgb(0,0,0,0.5))
```

```{r}
library(rgl)
# Multi 3D plot
plot3d(comp$PC1, comp$PC2, comp$PC3)
plot3d(comp$PC1, comp$PC3, comp$PC4)

# Determine the correct number of clusters via weighted sum of squares

wss <- (nrow(comp)-1)*sum(apply(comp,2,var))
for (i in 2:15) wss[i] <- sum(kmeans(comp, centers=i, nstart=100, iter.max=1000)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters",
     ylab="Within groups sum of squares")
```

```{r}
# From scree plot elbow occurs at k = 4
# Apply k-means with k=4
k <- kmeans(comp, 4, nstart=25, iter.max=1000)
library(RColorBrewer)
library(scales)
palette(alpha(brewer.pal(9,'Set1'), 0.5))
plot(comp, col=k$clust, pch=16)
```

```{r}
# 3D plot
plot3d(comp$PC1, comp$PC2, comp$PC3, col=k$clust)
plot3d(comp$PC1, comp$PC3, comp$PC4, col=k$clust)

# Cluster sizes
sort(table(k$clust))
```

```{r}
clust <- names(sort(table(k$clust)))

# First cluster
row.names(data[k$clust==clust[1],])
```

```{r}
# Second Cluster
row.names(data[k$clust==clust[2],])
```

```{r}
# Third Cluster
row.names(data[k$clust==clust[3],])
```

```{r}
# Fourth Cluster
row.names(data[k$clust==clust[4],])
```

```{r}
# Compare accommodation by cluster in boxplot
boxplot(data$Accommodation ~ k$cluster, 
        xlab='Cluster', ylab='Accommodation', 
        main='Plane Accommodation by Cluster')
```

```{r}
# Compare presence of seat classes in largest clusters
data[k$clust==clust[3],30:33]
```

```{r}
data[k$clust==clust[4],30:33]
```

